import time

print("Definitely not a Phishing Scam")
print()
time.sleep(0.4)
myName=input("Your Name:  ")
print(f"Thanks for logging in, {myName}")
print()
time.sleep(0.4)
cardNumber=input("What is your credit card number:  ")
print(f"Thanks, I definitely wont put {cardNumber} into Amazon and order anything weird")
print()
time.sleep(0.4)
print("Promise")
print()
time.sleep(0.4)
maidenName=input("What is your Mother's maiden name:  ")
print()
time.sleep(0.4)
print("That's cool, I just wanted to know that")
print()
time.sleep(0.4)
print(f"{maidenName} was your Mum's maiden name. Not because the bank requested it or anything, honest.")