print("\033[31m==== SKYRIM PYTHON EDITION ====\033[0m")
print("")
print("Welcome to Skyrim Python Edition!")
print("")
print("")
print("Hey you, you're finally awake! What is your name, adventurer?")
player_name = input("Your Name: ")
print("")
print("Welcome,", player_name + ". I'm sure you're ready to go on your first adventure!")
print("")
print("But first, fill in this Imperial Census, could you please?")
print()
print(player_name + ", what race are you?")
player_race = input("Race: ")
print("")
print("What is your profession,", player_name, "?")
player_class = input("Class: ")
print("")
print(player_name, "What is your gender?")
player_gender = input("Gender: ")
print("")
print("Well done", player_name, "the", player_gender, player_class + ", you made it to the end of the census! Now, let's get you started on your adventure!")